production:
  adapter: postgresql
  database: yodlee_production
  host: localhost
  username: postgres
  password: 123456
  encoding: utf8

development:
  adapter: postgresql
  database: yodlee_production
  host: localhost
  username: postgres
  password: 123456
  encoding: utf8

